homework/evgeny_shit/shit_file.txt

Creating a shit_file in the evgeny_shit folder.

---

homework/kate_hushcha/my_test_file.txt

initial commit

---

homework/alex_v/file.txt

add file.txt

---

homework/dmitrii_kiselev/file.txt

request dmitrii_kiselev_commit_homework

dmitrii_kiselev_commit_homework

---

homework/evgeny_shit/Homework_3/arithmetic_and_geometric_mean.py
homework/evgeny_shit/Homework_3/hypotenuse_and_area.py
homework/evgeny_shit/Homework_3/sum_difference_product.py
homework/evgeny_shit/Homework_3/сomplex_operation.py

Homework #3 has been completed

Evgeny: Homework_3 completed

---

homework/alex_v/homework4/task4.py

Homework 4

---

homework/dmitrii_kiselev/Homework_5/task1.py
homework/dmitrii_kiselev/Homework_5/task2.py
homework/dmitrii_kiselev/Homework_5/task3.py
homework/dmitrii_kiselev/Homework_5/task4.py

homework_5_done
Мне кажетя в 4-м задании можно поизящнее сделать - но я не смог придумать

homework_5_done

---

homework/alex_v/homework6/task6.1.py
homework/alex_v/homework6/task6.2.py

Lesson 6 :  Loops and conditions

Alex_ v homework6

---

homework/alex_v/homework7/task7.1.py
homework/alex_v/homework7/task7.2.py
homework/alex_v/homework7/task7.3.py

Alex_v homework7

---

homework/dmitrii_kiselev/Homework_6/json.json
homework/dmitrii_kiselev/homework_8/task_1.py

dmitrii_homework_8_done

---

homework/alex_v/homework9/hometask9.1.py

add 9.1 task

---

homework/alex_v/homework17/sql_task.py

Alex v homework17

---

homework/dmitrii_kiselev/final_fantasy/analyzer.py

При инициализации программы, кроме обязательного именнованного параметра --text можно добавить необязательные параметры --ignore_capitalize и --words_count. Первый ищет строгое вхождение подстроки, второй выдает указанное кол-во слов до и после найденного вхождения (по дефолту 5 слов до и после).
Найденное вхождение подстроки программа выделяет кавычками в ответе.

dmitrii_final_work_done

---

homework/alex_v/homework18/task18.1.py

Alex v homework18

---

homework/alex_v/homework20/hometask20.py

 home task 20

---

homework/alex_v/homework21/pytest.ini
homework/alex_v/homework21/test_api_pytest.py

Api , fixtures, annotation usage

Alex homework21

---

test_api_dmitrii/conftest.py
test_api_dmitrii/endpoints/base_api.py
test_api_dmitrii/endpoints/delete_post.py
test_api_dmitrii/endpoints/get_all_posts.py
test_api_dmitrii/endpoints/get_post.py
test_api_dmitrii/endpoints/patch_post.py
test_api_dmitrii/endpoints/post_post.py
test_api_dmitrii/endpoints/put_post.py
test_api_dmitrii/other_checks/other_checks.py
test_api_dmitrii/tests/data/headers.py
test_api_dmitrii/tests/data/payloads.py
test_api_dmitrii/tests/data/url.py
test_api_dmitrii/tests/test_api.py
test_api_dmitrii/tests/test_simple.py

Один зайфейленный тест - это по плану

dmitrii_hw24_api_done

---

api_tests_shit/client.py
api_tests_shit/conftest.py
api_tests_shit/endpoints/base_api.py
api_tests_shit/endpoints/delete_del_obj.py
api_tests_shit/endpoints/get_all_obj.py
api_tests_shit/endpoints/get_single_obj.py
api_tests_shit/endpoints/patch_part_upd_obj.py
api_tests_shit/endpoints/post_add_obj.py
api_tests_shit/endpoints/put_upd_obj.py
api_tests_shit/endpoints/schemas.py
api_tests_shit/pytest.ini
api_tests_shit/tests/data/payloads.py
api_tests_shit/tests/test_rest_api.py

Кажется, я начинаю уже злоупотреблять всякими "улучшениями", код становится менее читабельным )

Evgeny: homework 24 completed

---

homework/alex_v/homework28/homework28.py

hometask 28

---

homework/dmitrii_kiselev/homework_26_lowcost/locustfile.py

Не сильно старался, просто покрыл позитивные (не только) тесты основоных эндпоинтов. Там наверняка можно с декораторами разобраться, чтобы они создавали и удаляли мем, чтобы бащу не захлямлять. Но я для простоты почти все в один тест засунул. Но есть проверка мема, которая в итоге иногда 404 отдает - что тоже может служить проверкой)

dmitrii lowcost

---

homework/dmitrii_kiselev/homework_28_selenium/test_selenium.py

Все равно у меня назад экран отскакивал... Очень странно. Мы не знаем что это такое. Если бы мы знали, что это такое...

dmitrii_hw_29_selenium_demoqa

---

homework/alex_v/homework30/sel_basics.py

UI selenium task 30

---

homework/alex_v/homework31/sel_basic.py

Alex v homework31

---

homework/alex_v/homework35/play_task.py

2nd and 3rd task

---

homework/dmitrii_kiselev/homework_35_playwright_basics/test_playwright_3.py

В третьем задании запрос иногда возвращал 'User does not exist.' а иногда 'Wrong password.'. Я так и не нашел закономерность и чтобы тест не падал я разрешил и тот и другой ответ.
Законно ли это?

dmitrii_hw_35_done

---

pw_test_ui_dmitrii/conftest.py
pw_test_ui_dmitrii/pages/base_page.py
pw_test_ui_dmitrii/pages/create_new_customer_account.py
pw_test_ui_dmitrii/pages/deals_page.py
pw_test_ui_dmitrii/pages/eco_friendly_supplies.py
pw_test_ui_dmitrii/pages/login_page.py
pw_test_ui_dmitrii/pages/my_account.py
pw_test_ui_dmitrii/pages/product_page.py
pw_test_ui_dmitrii/pages/sales_page.py
pw_test_ui_dmitrii/tests/test_luma.py

Закончил
С одной стороны - легко
С другой стороны:
- как будто написать с нуля правильнее - есть много решений, которые не выглядят оптимально по PW, но переписывать - это вникать очень шоубого, поэтому оставляем как есть. Кроме того нет уверенности что все тесты корректно прошли и нет ложно полодительных
- очень нестабильно шли тесты - ошибка почти при каждом прогоне, но каждый раз разный тест фелится - прогоняешт этот тест отдельно - почти всегда ок, прогоняешт все - другой фейлится... Задолбался искать фейлы, просто под конец уже крутил-крутил...
- там один селект (опшн) нажималсся через раз почему-то

dmitrii_hw36_pw_ui_done
